### ISSUE TITLE
Firefox 39.0 and Greasemonkey 3.2 require @grant GM_addStyle

### ISSUE THREAD

**Issue by MagicAndCats** [KradekMFC/MFCAssistant#11]
Hello,

It appears that more recent versions of Greasemonkey prefer that Greasemonkey APIs be explicitly granted privileges to run. (http://wiki.greasespot.net/@grant) 

When I add the following API grant line the script now runs fine in Firefox / Greasemonkey:

// @grant GM_addStyle

I think this is the same issue experienced by the previous poster - I will post a message on that issue as well, in case that user is still monitoring this project :-)

I have been using MFC Assist for months in Chrome with the Tampermonkey addin and it works perfectly. 

I still find it very useful, thank-you!

**Comment by KradekMFC** [comment]
If you would like to submit a pull request Ill merge it. I simply haven’t been maintaining this script myself.

**Comment by KradekMFC** [comment]
Merged your request. Thank you for taking the time!
