### ISSUE TITLE
timeout errors 

### ISSUE THREAD

**Issue by elrcastor** [KradekMFC/MFCAssistant#9]
{"reason":"","code":1005,"wasClean":true,"path":{"length":0},"cancelBubble":false,"returnValue":true,"srcElement":{"binaryType":"blob","extensions":"","protocol":"","bufferedAmount":17,"readyState":3,"url":"ws://xchat12.myfreecams.com:8080/fcsl","URL":"ws://xchat12.myfreecams.com:8080/fcsl"},"defaultPrevented":false,"timeStamp":1408851114673,"cancelable":false,"bubbles":false,"eventPhase":0,"currentTarget":{"binaryType":"blob","extensions":"","protocol":"","bufferedAmount":17,"readyState":3,"url":"ws://xchat12.myfreecams.com:8080/fcsl","URL":"ws://xchat12.myfreecams.com:8080/fcsl"},"target":{"binaryType":"blob","extensions":"","protocol":"","bufferedAmount":17,"readyState":3,"url":"ws://xchat12.myfreecams.com:8080/fcsl","URL":"ws://xchat12.myfreecams.com:8080/fcsl"},"type":"close"}

i've been seeing errors like this more frequently lately, i've rebooted and such, is there any adjustments that can be made that will help with this?

**Comment by KradekMFC** [comment]
Unrelated to this project.
